### PR TITLE
bump meow and sax

### PR DESCRIPTION
**Pull request by flaport**
this should fix the meow issues.

### CODE REVIEW

**Comment by joamatab** [comment]
meow still fails

**Comment by joamatab** [comment]
any idea why?

**Comment by flaport** [comment]
It works on my computer. Can you point me to where/what exactly is failing?

**Comment by flaport** [comment]
@joamatab , I re-ran the failing CI job for meow and it's passing now. Probably the 0.9.0 library was not yet published on pypi when I pushed this fix to gplugins.

**Review by joamatab — APPROVED** [review]

**Comment by joamatab** [comment]
Thank you Floris!

**Pull request merged**
