### PR TITLE
Replace black with ruff-format

### LINKED ISSUE #236: Use ruff instead of black
Now that ruff has a [built-in formatter](https://docs.astral.sh/ruff/formatter/) that is (mostly) identical to black, maybe we should use that instead? It's faster, but most of all it's one less dependency.

### PR DESCRIPTION
**Pull request by yaugenst**
Closes #236

### CODE REVIEW

**Comment by yaugenst** [comment]
pre-commit.ci is failing because I enabled ruff's E501 along with removing black. We can disable it again if we want to ignore line length.

**Comment by joamatab** [comment]
how about merging the tidy3d branch first?

**Comment by yaugenst** [comment]
they are independent

**Review by joamatab — APPROVED** [review]

**Comment by joamatab** [comment]
https://github.com/gdsfactory/gplugins/pull/250

**Pull request closed without merging**
