### PR TITLE
Consolidate gmsh plugin

### PR DESCRIPTION
**Pull request by simbilod**
Remove all legacy meshing code, rely entirely on meshwell

First step towards making the plugin compliant with the new interface #142

### CODE REVIEW

**Comment by joamatab** [comment]
looks great Simon 

tests are still failing for the docs

https://github.com/gdsfactory/gplugins/actions/runs/6252637081/job/16976318317

**Comment by simbilod** [comment]
> looks great Simon
> 
> tests are still failing for the docs
> 
> https://github.com/gdsfactory/gplugins/actions/runs/6252637081/job/16976318317

Fixed!

**Comment by joamatab** [comment]
Thank you Simon!

**Comment by simbilod** [comment]
@mdecea this was the PR

**Pull request merged**
