### PR TITLE
Improve CICD

### LINKED ISSUE #7: scalable way for testing and documenation
as we increase the number of plugins, the tests and the documentation build time is going to increase

how can we run in paralel?

### PR DESCRIPTION
**Pull request by joamatab**
- add test_matrix  for testing in paralell
- rename to better names
  - rename gplugins.eme to gplugins.meow
  - rename gplugins.fem to gplugins.femwell
  - rename gplugins.gtidy3d to gplugins.tidy3d

fixes #7

### CODE REVIEW

**Comment by joamatab** [comment]
@momchil-flex

something in tidy3d seems to be failing now that I enabled dispersive materials by default

image

**Comment by momchil-flex** [comment]
I get these errors when I try to run locally

```
2023-08-03 11:11:25.619 | INFO     | gdsfactory.component:_write_library:1968 - Wrote to '/tmp/gdsfactory/straight_length2.gds'
2023-08-03 11:11:25.621 | WARNING  | gdsfactory.klive:show:48 - Could not connect to klive server. Is klayout open and klive plugin installed?
____________________________________________________________________________________ test_sparameters_grating_coupler _____________________________________________________________________________________
gplugins/gtidy3d/tests/test_write_sparameters_grating_coupler.py:19: in test_sparameters_grating_coupler
    dfs = [
gplugins/gtidy3d/tests/test_write_sparameters_grating_coupler.py:20: in <listcomp>
    gt.write_sparameters_grating_coupler(
../../../miniconda3/envs/gdsfactory/lib/python3.10/site-packages/gplugins/gtidy3d/write_sparameters_grating_coupler.py:117: in write_sparameters_grating_coupler
    sim = get_simulation_grating_coupler(
../../../miniconda3/envs/gdsfactory/lib/python3.10/site-packages/gplugins/gtidy3d/get_simulation_grating_coupler.py:318: in get_simulation_grating_coupler
    medium=get_medium(name_or_index=clad_material_name_or_index),
../../../miniconda3/envs/gdsfactory/lib/python3.10/site-packages/gplugins/gtidy3d/materials.py:98: in get_medium
    elif name_or_index in material_name_to_medium:
E   TypeError: unhashable type: 'numpy.ndarray'
------------------------------------------------------------------------------------------ Captured stdout call -------------------------------------------------------------------------------------------
2023-08-03 11:11:25.642 | INFO     | gdsfactory.component:_write_library:1968 - Wrote to '/tmp/gdsfactory/grating_coupler_ellipti_3efea4b2.gds'
2023-08-03 11:11:25.658 | WARNING  | gdsfactory.klive:show:48 - Could not connect to klive server. Is klayout open and klive plugin installed?
========================================================================================= short test summary info =========================================================================================
FAILED gplugins/gtidy3d/tests/test_simulation.py::test_simulation - TypeError: unhashable type: 'numpy.ndarray'
FAILED gplugins/gtidy3d/tests/test_write_sparameters.py::test_sparameters_straight_3d - TypeError: unhashable type: 'numpy.ndarray'
FAILED gplugins/gtidy3d/tests/test_write_sparameters.py::test_sparameters_straight_2d - TypeError: unhashable type: 'numpy.ndarray'
FAILED gplugins/gtidy3d/tests/test_write_sparameters_grating_coupler.py::test_sparameters_grating_coupler - TypeError: unhashable type: 'numpy.ndarray'
```

**Comment by momchil-flex** [comment]
Oh right sorry. By the way how do you develop locally? If I try running `pytest gplugins/gtidy3d/tests/` it complains that I don't have gplugins installed. And I can't `pip install -e ./`, so I ended up just doing `pip install ./`, but then I have to redo it every time the code changes.

**Comment by joamatab** [comment]
`pip install -e .` installs it in developer mode so you link the code and you only need to do it once

**Comment by momchil-flex** [comment]
Yeah that's what I wanted to do but it told me
```
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /home/momchil/Drive/flexcompute/gplugins
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
```

**Comment by joamatab** [comment]
are you on python>=3.10 ?

**Comment by momchil-flex** [comment]
Yeah python 3.10 works thanks.

Ok so I figured out what causes the issue, even though I don't fully understand it. But the underlying reason is that the mode monitor terminates exactly at the substrate on the z- direction:

image

For some reason, this causes it to error at one of the frequencies. I assume something to do with the very last pixel being different, and that's where we apply the PEC boundary condition. I found two possible solutions
- move the mode solver plane a little or make it smaller in that direction so that it doesn't touch the substrate (or if you want to take the substrate into account, then expand it so that it covers more of it, but then you may have to also make sure you're looking at the right mode and not a substrate mode).
- change [this line](https://github.com/gdsfactory/gplugins/blob/66c078bd5b9eed4e9d01f3cd80b4fa13dc1f3bde/gplugins/tidy3d/get_simulation_grating_coupler.py#L393) to `mode_spec=td.ModeSpec(num_modes=1, precision="double")`.

Ideally it's better to use the first approach throughout gdsfactory to make sure that mode planes are not exactly aligned with substrates. Similarly if the second approach is taken, it would probably be best to set double precision everywhere. Running this may be a little bit slower (and a bit more expensive) though.

We're also in the process of refactoring our remote mode solver. It may be that this will also fix this particular error.

By the way: regarding using dispersive models by default - they are also slower and more expensive to simulate. They also have a higher chance of diverging in some cases. Are you sure you want to start using those by default instead of making it easy for the user to toggle them on?

**Comment by joamatab** [comment]
Thank you Momchil, the tests are passing now, i implemented both of your suggestions, thank you for your help

I also went back to non dispersive models by default

**Comment by joamatab** [comment]
actually the tests are still failing remotely

not sure why they pass locally

https://github.com/gdsfactory/gplugins/actions/runs/5756010767/job/15604642415

**Pull request merged**
